ALTER TABLE day_names DROP CONSTRAINT day_names_weekday_index_unique;
ALTER TABLE pay_level_day_rules DROP CONSTRAINT pay_level_day_rules_unique;
ALTER TABLE roster_days DROP CONSTRAINT roster_days_unique;
ALTER TABLE roster_weeks DROP CONSTRAINT roster_weeks_week_offset_unique;
ALTER TABLE venue_config DROP CONSTRAINT venue_config_is_singleton_unique;
ALTER TABLE leave_requests DROP CONSTRAINT leave_requests_staff_id_fk;
ALTER TABLE pay_level_day_rules DROP CONSTRAINT pay_level_day_rules_day_name_id_fk;
ALTER TABLE pay_level_day_rules DROP CONSTRAINT pay_level_day_rules_pay_level_id_fk;
ALTER TABLE roster_days DROP CONSTRAINT roster_days_roster_week_id_fk;
ALTER TABLE roster_slots DROP CONSTRAINT roster_slots_roster_day_id_fk;
ALTER TABLE roster_slots DROP CONSTRAINT roster_slots_shift_type_id_fk;
ALTER TABLE roster_slots DROP CONSTRAINT roster_slots_slot_name_id_fk;
ALTER TABLE roster_slots DROP CONSTRAINT roster_slots_staff_id_fk;
ALTER TABLE shift_types DROP CONSTRAINT shift_types_default_pay_level_id_fk;
ALTER TABLE staff_availability DROP CONSTRAINT staff_availability_staff_id_fk;
ALTER TABLE staff DROP CONSTRAINT staff_user_id_fk;
ALTER TABLE timesheet_entries DROP CONSTRAINT timesheet_entries_approved_by_user_id_fk;
ALTER TABLE timesheet_entries DROP CONSTRAINT timesheet_entries_staff_id_fk;
ALTER TABLE users ADD CONSTRAINT users_role_valid CHECK (role IN ('staff', 'manager', 'admin'));
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_status_valid CHECK (status IN ('pending', 'approved', 'denied'));
ALTER TABLE timesheet_entries ADD CONSTRAINT timesheet_entries_approval_consistency CHECK (((NOT is_approved) AND approved_at IS NULL AND approved_by_user_id IS NULL) OR (is_approved AND approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL));
