module Web.Routes where
import Generated.Types
import IHP.RouterPrelude
import Web.Types

-- Generator Marker
instance AutoRoute StaticController
instance AutoRoute SessionsController
instance AutoRoute UsersController
instance AutoRoute DashboardController
instance AutoRoute ProfilesController
instance AutoRoute TimesheetsController
instance AutoRoute LeaveRequestsController
instance AutoRoute AdminController
instance AutoRoute StaffController
instance AutoRoute RosterWeeksController
